"""
Generates the transport icon sheet for Jukeblock.

The icons are hand-authored pixel art rather than drawn shapes: Minecraft's UI is
pixel art, and at GUI scale 4 every pixel is four screen pixels, so anything
anti-aliased or off-grid reads as mush. Each glyph is 16x16, pure white with an
alpha channel, so the panel can tint it per state (accent when active, grey when
the source doesn't support it).

    python tools/icons/make_icons.py

Writes src/main/resources/assets/jukeblock/textures/gui/icons.png, plus a
magnified preview next to this script for eyeballing changes.
"""

import os
import zlib
import struct

SIZE = 16

# '#' opaque, '.' transparent. Order here is the order in the sheet, and must match
# PlayerScreen.Glyph.
GLYPHS = {}

GLYPHS["previous"] = """
................
................
................
..##.......#....
..##......##....
..##.....###....
..##....####....
..##...#####....
..##...#####....
..##....####....
..##.....###....
..##......##....
..##.......#....
................
................
................
"""

GLYPHS["play"] = """
................
................
................
.....#..........
.....##.........
.....###........
.....####.......
.....#####......
.....#####......
.....####.......
.....###........
.....##.........
.....#..........
................
................
................
"""

GLYPHS["pause"] = """
................
................
................
....##....##....
....##....##....
....##....##....
....##....##....
....##....##....
....##....##....
....##....##....
....##....##....
....##....##....
....##....##....
................
................
................
"""

GLYPHS["next"] = """
................
................
................
....#.......##..
....##......##..
....###.....##..
....####....##..
....#####...##..
....#####...##..
....####....##..
....###.....##..
....##......##..
....#.......##..
................
................
................
"""

# Two tails on the left, diagonals that cross in the middle, solid arrowheads on the
# right. The heads are deliberately 3px deep — anything shallower reads as a kink in
# the line rather than an arrow.
GLYPHS["shuffle"] = """
................
................
............#...
............##..
.#####.....####.
.....##...####..
......##.##.#...
.......###......
.......###......
......##.##.#...
.....##...####..
.#####.....####.
............##..
............#...
................
................
"""

# A loop needs solid arrowheads or it just reads as a broken rectangle. The heads sit
# diagonally opposite so the glyph is rotationally symmetric.
GLYPHS["repeat"] = """
................
............#...
............##..
.....######.###.
....##########..
...##......##...
...##......##...
...##......##...
...##......##...
...##......##...
...##......##...
..##########....
.###.######.....
..##............
...#............
................
"""

GLYPHS["repeat_one"] = """
................
............#...
............##..
.....######.###.
....##########..
...##...#..##...
...##..##..##...
...##...#..##...
...##...#..##...
...##..###.##...
...##......##...
..##########....
.###.######.....
..##............
...#............
................
"""


def parse(pattern):
    rows = [r for r in pattern.strip("\n").split("\n") if r]
    assert len(rows) == SIZE, f"expected {SIZE} rows, got {len(rows)}"
    for r in rows:
        assert len(r) == SIZE, f"expected {SIZE} cols, got {len(r)}: {r!r}"
    return rows


def write_png(path, width, height, rgba):
    """Minimal RGBA PNG writer — avoids depending on PIL for the shipped asset."""
    raw = b"".join(
        b"\x00" + bytes(rgba[y * width * 4:(y + 1) * width * 4]) for y in range(height)
    )

    def chunk(tag, data):
        c = struct.pack(">I", len(data)) + tag + data
        return c + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)

    png = b"\x89PNG\r\n\x1a\n"
    png += chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0))
    png += chunk(b"IDAT", zlib.compress(raw, 9))
    png += chunk(b"IEND", b"")
    with open(path, "wb") as f:
        f.write(png)


def main():
    names = list(GLYPHS)
    sheet_w = SIZE * len(names)
    buf = bytearray(sheet_w * SIZE * 4)

    for index, name in enumerate(names):
        rows = parse(GLYPHS[name])
        for y, row in enumerate(rows):
            for x, ch in enumerate(row):
                if ch != "#":
                    continue
                px = (y * sheet_w + index * SIZE + x) * 4
                buf[px:px + 4] = b"\xff\xff\xff\xff"

    here = os.path.dirname(os.path.abspath(__file__))
    repo = os.path.abspath(os.path.join(here, "..", ".."))
    out = os.path.join(repo, "src", "main", "resources", "assets", "jukeblock",
                       "textures", "gui", "icons.png")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    write_png(out, sheet_w, SIZE, buf)
    print(f"wrote {out}  ({sheet_w}x{SIZE}, {len(names)} icons)")
    print("order:", ", ".join(names))

    # Magnified preview on a mid grey, so both the glyph and its holes are visible.
    scale = 10
    pw, ph = sheet_w * scale, SIZE * scale
    prev = bytearray()
    for y in range(ph):
        for x in range(pw):
            sx, sy = x // scale, y // scale
            px = (sy * sheet_w + sx) * 4
            if buf[px + 3]:
                prev += b"\xff\xff\xff\xff"
            else:
                # checker so glyph edges are readable against the background
                shade = 0x3A if ((sx // 2 + sy // 2) % 2) else 0x2E
                prev += bytes((shade, shade, shade + 6, 0xFF))
    write_png(os.path.join(here, "preview.png"), pw, ph, prev)
    print("preview written next to this script")


if __name__ == "__main__":
    main()
